### ISSUE TITLE
Pixelmon crash report

### ISSUE THREAD

**Issue by Heriptik** [josephworks/AtomMC#114]
Hello, i tested Pixelmon 7.2.0 (server) in Atom and i have a crash repport :

java.lang.NullPointerException: Exception in server tick loop
	at com.pixelmonmod.pixelmon.worldGeneration.dimension.ultraspace.UltraSpaceWorldProvider.func_76572_b(UltraSpaceWorldProvider.java:23)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:39)
	at net.minecraft.world.World.<init>(World.java:209)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:137)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:287)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:272)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by josephworks** [comment]
Hello,
I believe your issue has finally been fixed in the latest version.
Please download from http://192.168.0.11:8080/job/AtomMC/job/master/lastSuccessfulBuild/artifact/build/libs/
be sure to replace your server's /library folder with the newest libraries.zip

**Comment by Heriptik** [comment]
I can't download at this adress

**Comment by josephworks** [comment]
sorry, the address is http://josephworks.ddns.net:8080/job/AtomMC/job/master/lastSuccessfulBuild/artifact/build/libs/

**Comment by josephworks** [comment]
does that address work?

**Comment by Heriptik** [comment]
It's good

**Comment by josephworks** [comment]
great!

**Comment by josephworks** [comment]
Try it out and tell me if it fixes the issue

**Comment by Heriptik** [comment]
Its build on Apr 25, 2020 ?

**Comment by josephworks** [comment]
Yep
