### ISSUE TITLE
player eat error

### ISSUE THREAD

**Issue by Pestek1210** [josephworks/AtomMC#132]
I have a problem when one of the players eats, the player is thrown from the server.

`[22:43:19] [pool-3-thread-9/INFO] [fr.xephi.authme.AuthMe]: [AuthMe] Pestek logged in!
[22:43:29] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /127.0.0.1:52352
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:507) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:245) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:194) ~[NetworkDispatcher$1.class:master-abbc6b9]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:233) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:149) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:786) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:394) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:635) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:528) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:707) ~[CraftEventFactory.class:master-abbc6b9]
        at net.minecraft.util.FoodStats.func_151686_a(FoodStats.java:40) ~[afp.class:?]
        at net.minecraft.item.ItemFood.func_77654_b(ItemFood.java:41) ~[aij.class:?]
        at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:246) ~[aip.class:?]
        at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2575) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1188) ~[oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2482) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1992) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:230) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:428) ~[oq.class:?]
        ... 9 more
[22:43:29] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Pestek lost connection: Internal server error
[22:43:29] [Server thread/INFO] [minecraft/DedicatedServer]: Pestek left the game`

**Comment by josephworks** [comment]
please use https://mclo.gs and paste the whole log.

**Comment by Nartsu55** [comment]
@josephworks 
I have new information the problem of food is located here (see the image) the class FoodLevelChangeEvent of Bukkit is not in your project (in any case on git)
![Capture](https://user-images.githubusercontent.com/58628547/81534416-4a42e000-9368-11ea-9ca4-14d18b868134.PNG)

**Comment by Nartsu55** [comment]
I found a better type of server with the latest version of forge and with the Bukkit / Spigot / paperMC / Forge integration and developped by Terrainwax in addition, I wish you a good continuation

**Comment by josephworks** [comment]
k

**Comment by josephworks** [comment]
Try magmafoundation/magma
